#
# LUK the disks
#

- name: Encrypt OSDs
  shell: /sbin/cryptsetup -q luksFormat {{ item }} {{ encrypt_key_folder }}/{{ key_file }}
  when:
  - use_same_encrypt_key
  - (ansible_os_family == "CentOS") or
    (ansible_os_family == "RedHat")
  tags:
  - encrypt
  with_items:
  - "{{ hdds }}"
