#
# Generate key(s) for the disk(s)
#

- name: Generate encryption file(s) for each disk
  shell: dd bs={{ encrypt_key_size }} count=4 if=/dev/urandom of={{ encrypt_key_folder }}/{{ item }}-key iflag=fullblock
  with_items:
  - "{{ hdds }}"
  when:
  - not use_same_encrypt_key
  tags:
  - encrypt

- name: Retrieve encryption key(s)
  fetch: src={{ encrypt_key_folder }}/{{ key_file }} dest=/var/tmp/{{ inventory_hostname }}-{{ item }}-key
  with_items:
  - "{{ hdds }}"
  when: not use_same_encrypt_key
  tags:
  - encrypt
