#
# Single KEY for all disks
#

- name: Check if the key exists
  stat: path={{ encrypt_key_folder }}/{{ key_file }}
  register: status
  when:
  - use_same_encrypt_key
  tags:
  - encrypt

- name: Generate unique encryption file for ALL disks
  shell: dd bs={{ encrypt_key_size }} count=4 if=/dev/urandom of={{ encrypt_key_folder }}/{{ key_file }} iflag=fullblock
  when:
  - use_same_encrypt_key
  - not status.stat.exists
  tags:
  - encrypt

- name: Retrieve encryption key
  fetch: src={{ encrypt_key_folder }}/{{ key_file }} dest=/var/tmp/{{ key_file }}-{{ inventory_hostname }} flat=yes
  when: use_same_encrypt_key
  tags:
  - encrypt
