#
# Pre-Requesites
#

- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
  - cryptsetup
  tags:
  - encrypt
  - packages
  when: (ansible_os_family == "CentOS") or
        (ansible_os_family == "RedHat")
